Allowing editing list of syndici given a building
SELab-2/Dr-Trottoir-3 pull request #278
Opened 2023-05-06 16:07 UTC by ChewingBever

Title says it all, the list of syndici for a building can now be edited using a PATCH request, just like the other way around.

2023-05-08 03:34 UTC, MaximStockmans approved these changes

2023-05-08 11:02 UTC, jchetti requested changes
I talked about this with @ChewingBever on discord and turns out the id's of the syndici saved in the buildings match the id of their syndicus field instead of their user ID, which makes it very hard to work with, so another solution will have to be found for this.
Or we will have to give up on this feature which would force users when creating a building to then go to the syndicus of that building's page and add the building, instead of being able to instantly add the syndicus when creating the building.

2023-05-08 11:46 UTC, ChewingBever commented
I'll be looking into whether I can solve this problem.

2023-05-17 10:51 UTC, jchetti approved these changes

2023-05-18 10:33 UTC, merged