Reset password links
SELab-2/Dr-Trottoir-3 pull request #321
Opened 2023-05-18 10:37 UTC by ChewingBever

Adds a "Reset Password" button on the login page that sends an email with a private link that can be used to reset the account's password. It's basically the same system as the invite links.

2023-05-18 18:46 UTC, MaximStockmans requested changes
![image](https://github.com/SELab-2/Dr-Trottoir-3/assets/57869882/2921d24f-b83b-47c9-9515-4096f8372e26)
Create new view (can be a copy of login view) that does not contain the password field for extra clarity. 

Should also make the reset password button not primary color, but just a subtle text line below the primary login button. See screenshot for a little example (source: figma login widget).

![image](https://github.com/SELab-2/Dr-Trottoir-3/assets/57869882/a46a269a-3923-450b-91ca-4e14da6c8539)

2023-05-20 07:56 UTC, ChewingBever commented
As requested, I've added a separate "reset password" page and made the original button more subtle, with some styling help from @LanderDurie :pray: 
![2023-05-20-09:49:14](https://github.com/SELab-2/Dr-Trottoir-3/assets/65709211/a808ca86-c8c0-4f93-84ab-67f58dd13bde)
![2023-05-20-09:51:19](https://github.com/SELab-2/Dr-Trottoir-3/assets/65709211/2f7a1a1e-5d50-4435-aa19-97bae9ea3c7e)

2023-05-20 12:18 UTC, LanderDurie approved these changes

2023-05-20 13:21 UTC, MaximStockmans approved these changes

2023-05-20 13:21 UTC, merged